export const activities = [
  'running',
  'cycling',
  'swimming',
  'yoga',
  'pilates',
  'weight lifting',
  'boxing',
  'kickboxing',
  'crossfit',
  'dancing',
  'rock climbing',
  'hiking',
  'rowing',
  'canoeing',
  'kayaking',
  'surfing',
  'skiing',
  'snowboarding',
  'skateboarding',
  'basketball',
  'soccer',
  'football',
  'rugby',
  'tennis',
  'badminton',
  'table tennis',
  'golf',
  'volleyball',
  'handball',
  'archery',
  'fencing',
  'horseback riding',
  'gymnastics',
  'martial arts',
  'taekwondo',
  'judo',
  'karate',
  'aikido',
  'bjj',
  'muay thai',
  'krav maga',
  'wrestling',
  'jogging',
  'power walking',
  'aerobics',
  'zumba',
  'spin class',
  'trail running',
  'triathlon training',
  'synchronized swimming',
  'water polo',
  'diving',
  'squash',
  'racquetball',
  'lacrosse',
  'field hockey',
  'ice hockey',
  'figure skating',
  'bouldering',
  'paragliding',
  'hang gliding',
  'bmx',
  'mountain biking',
  'motorsport',
  'sailing',
  'windsurfing',
  'kitesurfing',
  'ultimate frisbee',
  'disc golf',
  'dodgeball',
  'softball',
  'cricket',
  'bowling',
  'curling',
  'bocce',
  'petanque',
  'sepak takraw',
  'capoeira',
  'parkour',
  'free running',
];
